// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDearj7o_7PbA4WMHaEFg9RTJUbijRAWfw',
    appId: '1:296522544686:web:45b41454d6860c1e0751bf',
    messagingSenderId: '296522544686',
    projectId: 'kiemtra-2351060461',
    authDomain: 'kiemtra-2351060461.firebaseapp.com',
    storageBucket: 'kiemtra-2351060461.firebasestorage.app',
    measurementId: 'G-JVRZG9T391',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx8oAF1vkE96wZNsI89izoZnsIMRjeSgg',
    appId: '1:296522544686:android:78c2b09bc3ac16180751bf',
    messagingSenderId: '296522544686',
    projectId: 'kiemtra-2351060461',
    storageBucket: 'kiemtra-2351060461.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj6TKcx65fvQt74YbIHuShpGTgi1gmxds',
    appId: '1:296522544686:ios:da86b0db4e5ce6530751bf',
    messagingSenderId: '296522544686',
    projectId: 'kiemtra-2351060461',
    storageBucket: 'kiemtra-2351060461.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp2351060461',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj6TKcx65fvQt74YbIHuShpGTgi1gmxds',
    appId: '1:296522544686:ios:da86b0db4e5ce6530751bf',
    messagingSenderId: '296522544686',
    projectId: 'kiemtra-2351060461',
    storageBucket: 'kiemtra-2351060461.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp2351060461',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDearj7o_7PbA4WMHaEFg9RTJUbijRAWfw',
    appId: '1:296522544686:web:55ed6182d1cd88a10751bf',
    messagingSenderId: '296522544686',
    projectId: 'kiemtra-2351060461',
    authDomain: 'kiemtra-2351060461.firebaseapp.com',
    storageBucket: 'kiemtra-2351060461.firebasestorage.app',
    measurementId: 'G-KCD2WPMTP6',
  );
}
